version: '3.8'

services:
  db:
    image: postgres:15
    container_name: fire_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fire_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d fire_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  ollama:
    image: ollama/ollama:latest
    container_name: fire_ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  api:
    build: .
    container_name: fire_api
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/fire_db
      - PYTHONPATH=/app
      - OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_MODEL=llama3.2:1b
      - GEMINI_API_KEY=${GEMINI_API_KEY} # Рекомендую передавать через .env файл
    depends_on:
      db:
        condition: service_healthy
      ollama:
        condition: service_started
    volumes:
      - .:/app
      - ./uploads:/app/uploads

  frontend:
    build: .
    container_name: fire_frontend
    restart: always
    ports:
      - "8501:8501"
    environment:
      - PYTHONPATH=/app
      - API_URL=http://api:8000 # Добавил переменную для связи фронта с бэком
    depends_on:
      - api
    volumes:
      - .:/app 
    command: streamlit run frontend/Streamlit_UI.py --server.port=8501 --server.address=0.0.0.0

  tg_bot:
    build: 
      context: . # или ./bot, если выделите в отдельную папку
    container_name: fire_tg_bot
    restart: always
    env_file:
      - .env
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - API_URL=http://api:8000 # Бот обращается к API по имени контейнера
    depends_on:
      - api
    command: python bot/main_bot.py # Команда запуска бота
volumes:
  postgres_data:
  ollama_data: